In [3]:
import numpy as np
numpy_array = np.array([1,2,3,4,5,6])
print(numpy_array)

type(numpy_array)
twoDArray = [[1,2,3],[5,6,7]]
print(twoDArray)

[1 2 3 4 5 6]
[[1, 2, 3], [5, 6, 7]]


In [4]:
# Create multi dimensionl arrays using numpy 
np.array([1,2,3,4,5],dtype=np.int32)

arr = [5.1,6.5,7,8.56,9]
np.array(arr,dtype=float)

boolArrr = np.array(arr,dtype=bool)
print(boolArrr)

[ True  True  True  True  True]


In [34]:
# arange function 
testArr = np.arange(2,18)
print(testArr)
testArr.reshape(2,8)
testArr.ndim

# size function to calculate the length of array
testArr1 = np.arange(2,100)
testArr1.size

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


98

In [53]:
arr2  = np.arange(1,10)
arr2.dtype
arr2 = arr2.reshape(3,3)
arr2.astype('float')


array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [84]:
arr3 = np.arange(1,10)
arr3.dtype
arr3 = arr3.reshape(3,3)
max_in_col = np.max(arr3,axis=0)
min_in_col = np.min(arr3,axis=0)

print(f'max value is {max_in_col} and min value is {min_in_col}')

np.sum(arr3,axis=1)

max value is [7 8 9] and min value is [1 2 3]


array([ 6, 15, 24])