In [2]:
import numpy as np
numpy_array = np.array([1,2,3,4,5,6])
print(numpy_array)

type(numpy_array)
twoDArray = [[1,2,3],[5,6,7]]
print(twoDArray)

[1 2 3 4 5 6]
[[1, 2, 3], [5, 6, 7]]


In [4]:
# Create multi dimensionl arrays using numpy 
np.array([1,2,3,4,5],dtype=np.int32)

arr = [5.1,6.5,7,8.56,9]
np.array(arr,dtype=float)

boolArrr = np.array(arr,dtype=bool)
print(boolArrr)

[ True  True  True  True  True]


In [34]:
# arange function 
testArr = np.arange(2,18)
print(testArr)
testArr.reshape(2,8)
testArr.ndim

# size function to calculate the length of array
testArr1 = np.arange(2,100)
testArr1.size

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


98

In [53]:
arr2  = np.arange(1,10)
arr2.dtype
arr2 = arr2.reshape(3,3)
arr2.astype('float')


array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [5]:
arr3 = np.arange(1,10)
arr3.dtype
arr3 = arr3.reshape(3,3)
max_in_col = np.max(arr3,axis=0)
min_in_col = np.min(arr3,axis=0)

print(f'max value is {max_in_col} and min value is {min_in_col}')

np.sum(arr3,axis=1)
np.prod(arr3,axis=1)


max value is [7 8 9] and min value is [1 2 3]


array([  6, 120, 504])

In [25]:
originalArr = np.arange(1,10).reshape(3,3)
print('Original Arr\n',originalArr)
print('Transpose Arr\n',originalArr.transpose())

np.ravel(originalArr)

Original Arr
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose Arr
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
arr_three = np.arange(1,9).reshape(2,2,2)
print(arr_three)
print('------------------------------------------')
print(arr_three[1])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
------------------------------------------
[[5 6]
 [7 8]]


In [118]:
arr_four = np.arange(1,17).reshape(4,4)
# print(arr_four)

# print(arr_four)

for i in np.nditer(arr_four):
    print(i)



1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


In [138]:
arr_1 = np.arange(1,13).reshape(3,4)
arr_2 = np.arange(13,25).reshape(3,4)

horizontal_arr = np.hstack((arr_1,arr_2))
print(horizontal_arr)

vertical_arr = np.vstack((arr_1,arr_2))
print(vertical_arr)

# spliting arr 

np.vsplit(vertical_arr,2)

np.hsplit(horizontal_arr,2)

[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])]